# This playbook stops the nginx service and removes the nginx package from all hosts
- hosts: all
  tasks:
    - name: stop nginx
      service:
          name: nginx
          state: stopped
    - name: ensure nginx is not installed
      apt: name=nginx state=absent