apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: wp-clcreative
spec:
  rules:
  - host: {{ .Values.portainer.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portainer
            port:
              number: {{ .Values.portainer.servicePort }}
