apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.toml: |
    [providers.cloudflare]
      apiKey = "$(CLOUDFLARE_API_KEY)"
      apiEmail = "$(CLOUDFLARE_API_EMAIL)"
      zone = "roadmaps.link"
