apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  labels:
    app: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
        - name: nginx-2
          image: phx.ocir.io/Jp6;G_QU)AqJYlV_#Eo)/free-kubernetes-nginx:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: free-registry-secret
